name: Deploy a development image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-dev

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Dockerfile

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        if: steps.changed.outputs.any_changed
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        if: steps.changed.outputs.any_changed
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.changed.outputs.any_changed

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.changed.outputs.any_changed

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        if: steps.changed.outputs.any_changed
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
