name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-dev:base

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt

      - name: Check format
        run: |
          cargo fmt -- --check
  test:
    name: Test all
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-dev:base

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable

      - name: Run test
        run: |
          cargo test
